web:
  build: .
  container_name: app_test
  command: python -u app.py
  ports:
    - "5001:5000"
  volumes:
    - .:/todo
  links:
    - db
db:
  image: mongo:4.0.9
  container_name: mongo_test
  volumes:
    - ./dockerdata:/data/db 
